### ISSUE TITLE
sapjvm link seems to be broken 

### ISSUE THREAD

**Issue by daniel-tejeda** [nzamani/sap-cloud-connector-docker#10]
Hi there, 
Trying this out today, sapcc-2.12.0.1-linux-x64.zip seems to be downloaded OK but sapjvm-8.1.053-linux-x64.rpm gives 404 Not Found when building the docker image. 

--2019-06-11 22:28:12--  https://tools.hana.ondemand.com/additional/sapjvm-8.1.053-linux-x64.rpm
Resolving tools.hana.ondemand.com (tools.hana.ondemand.com)... 23.198.156.49
Connecting to tools.hana.ondemand.com (tools.hana.ondemand.com)|23.198.156.49|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 404 Not Found
  Content-Type: text/html
  Server: SAP
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Date: Tue, 11 Jun 2019 22:44:26 GMT
  Content-Length: 8933
  Connection: keep-alive
2019-06-11 22:28:13 ERROR 404: Not Found.

Right link: https://tools.hana.ondemand.com/additional/sapjvm-8.1.055-linux-x64.rpm

Cheers

**Comment by nzamani** [comment]
Thanks - fixed with ab6191a5d5c9ba902d7a2055168e7cb3edf5e2cf
