### ISSUE TITLE
New JVM-Version 

### ISSUE THREAD

**Issue by Griesmar** [nzamani/sap-cloud-connector-docker#14]
Hi,
on tools.hana.ondemand.com is a new JVM version available (sapjvm-8.1.059-linux-x64.rpm). I have found this as I got an error by building of the Dockerimage. after changing of my local Dockerfile to the new version, the build was successful.

**Comment by nzamani** [comment]
Thanks for this. A Pull Request would've fit in here perfectly. Anyways, it's fixed soon...
