### ISSUE TITLE
sapcc download url changed

### ISSUE THREAD

**Issue by eguo** [nzamani/sap-cloud-connector-docker#15]
># In such cases please also let me know by opening an issue so that I can update this dockerfile.
The sapcc download url has changed.  This is what working for me today (2019-12-09): https://tools.hana.ondemand.com/additional/sapcc-2.12.2-linux-x64.zip

**Comment by nzamani** [comment]
Thanks & sorry for being late. I should probably update the documentation and ask for pull requests :-)
