### ISSUE TITLE
sapcc-2.12.1.1-linux-x64.zip  returning 404

### ISSUE THREAD

**Issue by cmedley** [nzamani/sap-cloud-connector-docker#19]
In Dockerfile, both of these files are returning a 404 ->
https://tools.hana.ondemand.com/additional/sapcc-2.12.1.1-linux-x64.zip
https://tools.hana.ondemand.com/additional/sapjvm-8.1.055-linux-x64.rpm

Will do a PR, but not clear where to find the new urls on tools.hana.ondemand.com

**Comment by cmedley** [comment]
Looks like these are the updated links ->
https://tools.hana.ondemand.com/additional/sapcc-2.12.2-linux-x64.zip
https://tools.hana.ondemand.com/additional/sapjvm-8.1.059-linux-x64.rpm

**Comment by abornn** [comment]
Hi @cmedley i'm using the setup you provisioned for the new version and using a diferent base image, oraclelinux:8 and the container is starting, when i try to access the localhost:8443 i do not see the page
i see the following 
![image](https://user-images.githubusercontent.com/60951129/74295426-a2852a00-4d06-11ea-98ba-8bb9e8fe95aa.png)

**Comment by cmedley** [comment]
@abornn   what happens if you use centos:7 as base image?    

When I use oraclelinux:8 as base image, I get /bin/sh: chsh: command not found  on RUN chsh -s /bin/bash sccadmin  line

What does your Dockerfile look like that produces your screenshot?

**Comment by abornn** [comment]
@cmedley using centos:7 im getting the same error.

This is my docker file:

FROM oraclelinux:7
RUN yum -y install initscripts which unzip wget net-tools less


WORKDIR /tmp/sapdownloads


RUN wget --no-check-certificate --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/sapcc-2.12.2-linux-x64.zip && \
  wget --no-check-certificate --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/sapjvm-8.1.059-linux-x64.rpm && \
  unzip sapcc-2.12.2-linux-x64.zip && \
  rpm -i sapjvm-8.1.059-linux-x64.rpm && \
  rpm -i com.sap.scc-ui-2.12.2-3.x86_64.rpm


RUN chsh -s /bin/bash sccadmin


EXPOSE 8443
USER sccadmin
WORKDIR /opt/sap/scc


CMD /opt/sapjvm_8/bin/java \
	-server \
  -XtraceFile=log/vm_@PID_trace.log \
  -XX:+GCHistory \
  -XX:GCHistoryFilename=log/vm_@PID_gc.prf \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+DisableExplicitGC \
  -Xms1024m \
  -Xmx1024m \
  -XX:MaxNewSize=512m \
  -XX:NewSize=512m \
  -XX:+UseConcMarkSweepGC \
  -XX:TargetSurvivorRatio=85 \
  -XX:SurvivorRatio=6 \
  -XX:MaxDirectMemorySize=2G \
  -Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=com.sap.scc.tomcat.utils.PropertyDigester \
  -Dosgi.requiredJavaVersion=1.6 \
  -Dosgi.install.area=. \
  -DuseNaming=osgi \
  -Dorg.eclipse.equinox.simpleconfigurator.exclusiveInstallation=false \
  -Dcom.sap.core.process=ljs_node \
  -Declipse.ignoreApp=true \
  -Dosgi.noShutdown=true \
  -Dosgi.framework.activeThreadType=normal \
  -Dosgi.embedded.cleanupOnSave=true \
  -Dosgi.usesLimit=30 \
  -Djava.awt.headless=true \
  -Dio.netty.recycler.maxCapacity.default=256 \
  -jar plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar

**Comment by cmedley** [comment]
@abornn  I used your dockerfile (adding back the \)  and it worked fine ..  what browser / OS are you using?

**Comment by abornn** [comment]
@cmedley I'm using Windows 10 and i tried in firefox and explorer

**Comment by cmedley** [comment]
@abornn  found colleague with windows 10  and docker and had them build and run that docker file.  Worked with no issues 
![windows10](https://user-images.githubusercontent.com/201315/74478878-3c221800-4e7c-11ea-84b4-1bd86bf51910.png)

While the container is running, if you open shell and 
```
$ curl https://localhost:8443 -k -v  
```
what is the output?

**Comment by abornn** [comment]
Hi i saw the issue i did not realize i was trying to acces via http insted o https, what a dumb error, thanks a lot for your help

**Comment by nzamani** [comment]
Thanks for your support, @cmedley ! :-)
