### ISSUE TITLE
New Version available

### ISSUE THREAD

**Issue by mlackner79** [nzamani/sap-cloud-connector-docker#23]
Hi,

there is a new version of sapcc available...

https://tools.hana.ondemand.com/additional/sapcc-2.12.4-linux-x64.zip

The RPM package changed to **com.sap.scc-ui-2.12.4-4.x86_64.rpm**

Please update the Dockerfile ;)

Regards,
Markus Lackner

**Comment by nzamani** [comment]
Thanks @mlackner79!
Meanwhile others have created pull requests which are now merged.
