### ISSUE TITLE
SAP JVM outdated - problem with current version

### ISSUE THREAD

**Issue by vogeltho86** [nzamani/sap-cloud-connector-docker#27]
Hello,

the SAP JVM version in the docker file is 8.1.063, the current version is 8.1.065. I've made a local copy of the docker file and changed the version to 8.1.065. Unfortunately I'm getting a error while accessing the cloud connector (no secure connection). Do you have any hints how to get the cloud connector running with JVM 8.1.065?

Many thanks,
Thomas

**Comment by nzamani** [comment]
SAP JVM was just updated via #28 from a PR by @rsletta 

"No secure connection" comes from your browser, right? That's normal, as the cert is not trusted. What you can simply do is clicking "open page anyway" or something similar.

Would be great if you'd check and confirm.

Thanks, Nabi

**Comment by vogeltho86** [comment]
Hi Nabi,

it is a different error. It seems to be related to the SAP JVM version. I had a try with an older local version (sapjvm-8.1.041) and sapcc-2.12.4, in that case it worked with the approach by clicking on "open page anyway". With SAP JVM 8.1.065 I'm getting the error below:

![image](https://user-images.githubusercontent.com/55950743/94524276-b4362600-0232-11eb-84ee-2af7610adfe8.png)

Do you have a hint what I could do to avoid this error? 

Many thanks,
Thomas

**Comment by tometzki** [comment]
hello,
i get the same error. I think it is an issue with the ssl certificate or with the browser security. 
Any solution for this issue ?

**Comment by tometzki** [comment]
Hello Together,

i found the issue. Add to the dockerfile: 

-Djdk.tls.server.protocols=TLSv1.2 \

in the section

**Comment by htammen** [comment]
I fixed this problem with my [PR-29](https://github.com/nzamani/sap-cloud-connector-docker/pull/29). As soon as @nzamani pulls it this will work as before, means you will have the chance to enter the page on your own risk.

**Comment by nzamani** [comment]
@vogeltho86 the pull request by @htammen has been merged, could you please try again?

**Comment by tometzki** [comment]
many thanks
