### ISSUE TITLE
Update JVM version in docker file

### ISSUE THREAD

**Issue by DChupris** [nzamani/sap-cloud-connector-docker#6]
Hi @nzamani.
Please update docker file with the latest version of sapJVM
Line 36: 
`    wget --no-check-certificate --no-cookies --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt; path=/;" -S https://tools.hana.ondemand.com/additional/sapjvm-8.1.052-linux-x64.rpm && \
`
And line 38:
`    rpm -i sapjvm-8.1.052-linux-x64.rpm && \
`
Thank you

**Comment by nzamani** [comment]
@DChupris thanks!

upgraded to 8.1.053 via merged pull request: https://github.com/nzamani/sap-cloud-connector-docker/pull/7
