### ISSUE TITLE
Update Cloud Connector Version 2.12.0.1

### ISSUE THREAD

**Issue by ahamebogu** [nzamani/sap-cloud-connector-docker#8]
Hello Nabi, 

The current version for SCC is 2.12.0.1 as references to the previous version used in the dockerfile have been deleted from download site.

And the JVM also.

Best Regards.
Aham.

**Comment by nzamani** [comment]
@ahamebogu thanks!

done via merged pull request: https://github.com/nzamani/sap-cloud-connector-docker/pull/7
