### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by jot-hub** [nzamani/sap-cloud-connector-docker#9]
issue happens at the following line:
> RUN service scc_daemon stop && chsh -s /bin/bash sccadmin

I did not get this error before (about 2 months ago) - I start to get it now

**Comment by nzamani** [comment]
thanks, this is fixed with https://github.com/nzamani/sap-cloud-connector-docker/commit/ec226eec16e69de52b153ee84c77c500b1272adf

**Comment by playfcode** [comment]
![image](https://user-images.githubusercontent.com/69490311/164960699-359b855f-e5a3-4245-b295-609e74462b89.png)
I got the issue again,
